name: Build and Test KMP Project

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build project (Android, Desktop, iOS)
        run: ./gradlew build

      - name: Run all tests
        run: ./gradlew check

  android:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build Android Debug APK
        run: ./gradlew assembleDebug

      - name: Run Android Unit Tests
        run: ./gradlew testDebugUnitTest

  ios:
    runs-on: macos-14
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew  # <-- FIXED: Added missing permission step

      - name: Install Xcode dependencies
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -runFirstLaunch

      - name: Build iOS Framework
        run: ./gradlew linkReleaseFrameworkIosX64

      - name: Run iOS Tests
        run: ./gradlew iosX64Test

  desktop:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build Desktop App
        run: ./gradlew packageDistributionForCurrentOS

      - name: Run Desktop Unit Tests
        run: ./gradlew test  # <-- FIXED: Changed jvmTest to test
